
-- Code below is not intended to be executed. It contains annotations for VSCode and other compatible IDEs.
-- More about Lua annotations format: https://luals.github.io/wiki/annotations
-- This file is auto-generated, do not edit it manually.

---@diagnostic disable: missing-return, lowercase-global, missing-fields


-----------------------------------------------------------
------ fyrox_lite::lite_ui::Color
-----------------------------------------------------------

---@class Color_static
---@field WHITE Color
---@field BLACK Color
---@field RED Color
---@field GREEN Color
---@field BLUE Color
---@field TRANSPARENT Color
---@field MAROON Color
---@field DARK_RED Color
---@field BROWN Color
---@field FIREBRICK Color
---@field CRIMSON Color
---@field TOMATO Color
---@field CORAL Color
---@field INDIAN_RED Color
---@field LIGHT_CORAL Color
---@field DARK_SALMON Color
---@field SALMON Color
---@field LIGHT_SALMON Color
---@field ORANGE_RED Color
---@field DARK_ORANGE Color
---@field ORANGE Color
---@field GOLD Color
---@field DARK_GOLDEN_ROD Color
---@field GOLDEN_ROD Color
---@field PALE_GOLDEN_ROD Color
---@field DARK_KHAKI Color
---@field KHAKI Color
---@field OLIVE Color
---@field YELLOW Color
---@field YELLOW_GREEN Color
---@field DARK_OLIVE_GREEN Color
---@field OLIVE_DRAB Color
---@field LAWN_GREEN Color
---@field CHARTREUSE Color
---@field GREEN_YELLOW Color
---@field DARK_GREEN Color
---@field FOREST_GREEN Color
---@field LIME Color
---@field LIME_GREEN Color
---@field LIGHT_GREEN Color
---@field PALE_GREEN Color
---@field DARK_SEA_GREEN Color
---@field MEDIUM_SPRING_GREEN Color
---@field SPRING_GREEN Color
---@field SEA_GREEN Color
---@field MEDIUM_AQUA_MARINE Color
---@field MEDIUM_SEA_GREEN Color
---@field LIGHT_SEA_GREEN Color
---@field DARK_SLATE_GRAY Color
---@field TEAL Color
---@field DARK_CYAN Color
---@field AQUA Color
---@field CYAN Color
---@field LIGHT_CYAN Color
---@field DARK_TURQUOISE Color
---@field TURQUOISE Color
---@field MEDIUM_TURQUOISE Color
---@field PALE_TURQUOISE Color
---@field AQUA_MARINE Color
---@field POWDER_BLUE Color
---@field CADET_BLUE Color
---@field STEEL_BLUE Color
---@field CORN_FLOWER_BLUE Color
---@field DEEP_SKY_BLUE Color
---@field DODGER_BLUE Color
---@field LIGHT_BLUE Color
---@field SKY_BLUE Color
---@field LIGHT_SKY_BLUE Color
---@field MIDNIGHT_BLUE Color
---@field NAVY Color
---@field DARK_BLUE Color
---@field MEDIUM_BLUE Color
---@field ROYAL_BLUE Color
---@field BLUE_VIOLET Color
---@field INDIGO Color
---@field DARK_SLATE_BLUE Color
---@field SLATE_BLUE Color
---@field MEDIUM_SLATE_BLUE Color
---@field MEDIUM_PURPLE Color
---@field DARK_MAGENTA Color
---@field DARK_VIOLET Color
---@field DARK_ORCHID Color
---@field MEDIUM_ORCHID Color
---@field PURPLE Color
---@field THISTLE Color
---@field PLUM Color
---@field VIOLET Color
---@field MAGENTA Color
---@field ORCHID Color
---@field MEDIUM_VIOLET_RED Color
---@field PALE_VIOLET_RED Color
---@field DEEP_PINK Color
---@field HOT_PINK Color
---@field LIGHT_PINK Color
---@field PINK Color
---@field ANTIQUE_WHITE Color
---@field BEIGE Color
---@field BISQUE Color
---@field BLANCHED_ALMOND Color
---@field WHEAT Color
---@field CORN_SILK Color
---@field LEMON_CHIFFON Color
---@field LIGHT_GOLDEN_ROD_YELLOW Color
---@field LIGHT_YELLOW Color
---@field SADDLE_BROWN Color
---@field SIENNA Color
---@field CHOCOLATE Color
---@field PERU Color
---@field SANDY_BROWN Color
---@field BURLY_WOOD Color
---@field TAN Color
---@field ROSY_BROWN Color
---@field MOCCASIN Color
---@field NAVAJO_WHITE Color
---@field PEACH_PUFF Color
---@field MISTY_ROSE Color
---@field LAVENDER_BLUSH Color
---@field LINEN Color
---@field OLD_LACE Color
---@field PAPAYA_WHIP Color
---@field SEA_SHELL Color
---@field MINT_CREAM Color
---@field SLATE_GRAY Color
---@field LIGHT_SLATE_GRAY Color
---@field LIGHT_STEEL_BLUE Color
---@field LAVENDER Color
---@field FLORAL_WHITE Color
---@field ALICE_BLUE Color
---@field GHOST_WHITE Color
---@field HONEYDEW Color
---@field IVORY Color
---@field AZURE Color
---@field SNOW Color
---@field DIM_GRAY Color
---@field GRAY Color
---@field DARK_GRAY Color
---@field SILVER Color
---@field LIGHT_GRAY Color
---@field GAINSBORO Color
---@field WHITE_SMOKE Color
Color = {}

---@class Color
Color_instance = {}

